# Generated by Django 4.2.16 on 2024-11-13 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_answer_likes_count_question_answer_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer_count',
            new_name='answers_count',
        ),
    ]
