# Generated by Django 4.2.16 on 2024-11-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, default='img/placeholder-pic.png', null=True, upload_to=''),
        ),
    ]
